### Building the ANN

In [5]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

In [6]:
data = pd.read_csv("Churn_Modelling.csv")

In [7]:
data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [8]:
tf.__version__

'2.4.1'

In [19]:
X = data.iloc[:,3:-1].values
y = data.iloc[:,-1].values #output columns (exit status)

In [21]:
#label encoder for gender column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [26]:
# One hot encoder for country
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [27]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [28]:
#train -test
from sklearn.model_selection import train_test_split
X_train,X_test,y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [31]:
#feature scaling-> fundamental
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [32]:
#building an ANN model
ann = tf.keras.models.Sequential()

In [33]:
#adding input layer
ann.add(tf.keras.layers.Dense(units= 6, activation= 'relu'))  #fully connected layer object

In [35]:
#adding 2nd hidden layer
ann.add(tf.keras.layers.Dense(units= 6, activation= 'relu'))

In [36]:
#adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation= 'sigmoid')) #as our dependent variable is binary units=1, activation function is: sigmoid (softmax for categorical)as it also gives the probability of outcomes

In [37]:
#Compiling the ANN
ann.compile(optimizer='adam', loss= 'binary_crossentropy', metrics=['accuracy']) #binary outcome


In [38]:
#Training the ANN
ann.fit(X_train, y_train, batch_size = 32, epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.6916 - accuracy: 0.5749
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4725 - accuracy: 0.8033
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4450 - accuracy: 0.8029
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4200 - accuracy: 0.8170
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4260 - accuracy: 0.8206
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4153 - accuracy: 0.8240
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3990 - accuracy: 0.8299
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3957 - accuracy: 0.8330
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3929 - accuracy: 0.8345
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3848 - accura

250/250 [==============================] - 0s 984us/step - loss: 0.3290 - accuracy: 0.8638
Epoch 81/100
250/250 [==============================] - 0s 979us/step - loss: 0.3212 - accuracy: 0.8691
Epoch 82/100
250/250 [==============================] - 0s 927us/step - loss: 0.3224 - accuracy: 0.8715
Epoch 83/100
250/250 [==============================] - 0s 981us/step - loss: 0.3366 - accuracy: 0.8619
Epoch 84/100
250/250 [==============================] - 0s 948us/step - loss: 0.3360 - accuracy: 0.8677
Epoch 85/100
250/250 [==============================] - 0s 915us/step - loss: 0.3357 - accuracy: 0.8600
Epoch 86/100
250/250 [==============================] - 0s 888us/step - loss: 0.3300 - accuracy: 0.8631
Epoch 87/100
250/250 [==============================] - 0s 964us/step - loss: 0.3362 - accuracy: 0.8613
Epoch 88/100
250/250 [==============================] - 0s 994us/step - loss: 0.3256 - accuracy: 0.8647
Epoch 89/100
250/250 [==============================] - 0s 985us/step - loss:

In [42]:
#Predicting the results
# Geography: France
# Credid score: 650
# Gender: Male
#Age: 40
# Tenure: 3 years
# Balance: 50000$
# Number of products: 2
# credicard: 1 (yes)
#acive member? (Yes)
#estimated salary: $45000
# What is the Customer churn status?
ann.predict(sc.transform([[1,0,0,650,1,40,3,50000,2,1,1,45000]]))  #any input of the predict method must be a 2-D array
# need to apply a transform as we did a feature scaling before building a model
# Outcome will be a probability as we used Sigmoid function for an output layer

array([[0.04732105]], dtype=float32)

In [43]:
print(ann.predict(sc.transform([[1,0,0,650,1,40,3,50000,2,1,1,45000]])) >0.5) # threshold 0f 0.5

[[False]]


#### hence customer won't leave the bank

In [49]:
# Predicting the test set results
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))    
                

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [51]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1583   12]
 [ 342   63]]


0.823